#!/bin/sh
if test -x /lib64 ; then
	libdir=/lib64
else
	libdir=/lib
fi
set -x -e
autoreconf -i -f
./configure --libdir=$libdir --sysconfdir=/etc --mandir=${TMPDIR:-/var/tmp}/autogen-man-tmp --enable-Werror
