.TH pam_krb5 5 2001/05/29 "Red Hat Linux" "System Administrator's Manual"
.SH NAME
pam_krb5 \- Kerberos 5 authentication with AFS support
.SH DESCRIPTION
pam_krb5.so uses a portion of \fBkrb5.conf\fR to get its configuration
information.  You should read the \fBkrb5.conf(5)\fR man page before continuing
here.  The module expects its configuration information to be in the \fBpam\fR
subsection of the \fBappdefaults\fP section of the \fBkrb5.conf\fR
configuration file.

.SH DIRECTIVES
.IP debug
can be set to \fBtrue\fR or \fBfalse\fR
turns on debugging via \fBsyslog(3)\fR.
.IP ticket_lifetime
default ticket lifetime.  If not specified, the default is 36000 seconds (10
hours).
.IP renew_lifetime
default renewable lifetime.  This specifies how much time you have after
getting credentials to renew them.  If not specified, the default is 36000
seconds (10 hours).
.IP forwardable
controls whether or not credentials are forwardable.  If not specified, they
are.
.IP krb4_convert
controls whether or not pam_krb5 tries to get Kerberos IV credentials from the
KC (or using the \fBkrb524d\fR service on the KDC) and create ticket files with
them.  Unless you've converted \fIeverything\fR on your network over to use
Kerberos 5, you'll want to leave this set to \fBtrue\fR.
.IP hosts
specifies which other hosts credentials obtained by pam_krb5 will be good on.
If your host is behind a firewall, you should add the IP address or name that
the \fIKDC\fR sees it as to this list.
.IP validate
specifies whether or not to attempt validation of the TGT.  The default is
\fBfalse\fP.
.IP required_tgs
specifies a principal for which a user must be able to get a session key for for
the purpose of verifying that the TGT has not been forged.  The key is
decrypted using a copy of the service's key stored in a local keytab file.
This is the only certain way to be absolutely sure the TGT hasn't been forged.
The default is \fBhost\fP@\fIhostname\fP.
.IP keytab
specifies the name of a keytab file to find a key for the \fBrequired_tgs\fP in,
for use in validating TGTs.  The default is \fB/etc/krb5.keytab\fP.
.IP ccache_dir
specifies the directory to place credential cache files in.  The default is
\fB/tmp\fR.
.IP banner
specifies what kind of password the module claims to be changing when called
to change passwords.  The default is \fBKerberos 5\fP.
.IP max_timeout
specifies the maximum amount of time to spend in attempting to get a reply
from the \fIKDC\fRs, in seconds. This in effect determines the amount of
time before PAM tries the next authentication scheme, if the network is 
not available.
.IP timeout_shift
specifies the number of bits left to shift after each timeout, in
implementing the incremental backoff in talking to the KDCs
.IP initial_timemout
specifies the number of seconds to wait for the first KDC to respond, before
attempting incremental backoff.
.IP addressless
disables the checking of the address in the ticket. Allows the ticket to be
used from behind NAT firewalls, or on machines whose IP address changes
regularly.

.SH EXAMPLE

[appdefaults]
  pam = {
    debug = true
    ticket_lifetime = 36000
    renew_lifetime = 36000
    forwardable = true
    krb4_convert = true
    hosts = thermo.example.edu alf.example.edu
    validate = true
    required_tgs = host/thermo.example.edu
    ccache_dir = /var/tmp
  }

.SH FILES
\fI/etc/krb5.conf\fP
.br
.SH "SEE ALSO"
.BR pam_krb5 (8)
.br
.SH BUGS
Possibly, but let's hope not.  If you find any, please email the author.
.SH AUTHOR
Nalin Dahyabhai <nalin@redhat.com>
